// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_userId_ from "./routes/api/[userId].ts";
import * as $api_raw_userId_ from "./routes/api/raw/[userId].ts";
import * as $index from "./routes/index.tsx";
import * as $Preview from "./islands/Preview.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
 routes: {
  "./routes/_404.tsx": $_404,
  "./routes/_app.tsx": $_app,
  "./routes/_middleware.ts": $_middleware,
  "./routes/api/[userId].ts": $api_userId_,
  "./routes/api/raw/[userId].ts": $api_raw_userId_,
  "./routes/index.tsx": $index,
 },
 islands: {
  "./islands/Preview.tsx": $Preview,
 },
 baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
