name: Deploy

on: [push, pull_request]

jobs:
 deploy:
  name: Deploy
  runs-on: ubuntu-latest

  permissions:
   id-token: write
   contents: read

  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v4

   - name: 🚀 Install deno
     uses: denoland/setup-deno@v2
     with:
      deno-version: v2.x

   - name: 🚀 Build project
     run: "deno task build"

   - name: 🚀 Upload to Deno Deploy
     uses: denoland/deployctl@v1
     with:
      project: "discord-activity"
      entrypoint: "server.ts"
      root: "."
